repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx-root
    namespace: default
    chart: bitnami/nginx
    values:
      - nginx-root-values/nginx-service-values.yaml
  - name: init-root
    namespace: default
    chart: ./init-chart

